/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-09-29

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "GPIO.h"
#include "stm32f4xx.h"
#include <stdbool.h>
#include "adc.h"
#include "delai.h"
#include "pwm.h"
#include <stdio.h>
#include "uart.h"
#include "spi.h"
#include "lcd_driver.h"

#define P1

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
volatile uint64_t millis_count = 0;

int main(void)
{
	#ifdef P1
	SysTick_Init(9000); // interruption a chaque 1ms
	UART5_Config();

	uint8_t data_recu;
	uint64_t last_hello = millis();
	uint64_t timestamp = millis();
	const char *hello = "Hello World!\n";

	while(1){
		timestamp = millis();
		if (timestamp - last_hello > 1000){ // envoie périodique de Hello World
			for (uint32_t i = 0; hello[i] != '\0'; i++){
				UART5_SendByte(hello[i]);
			}
			last_hello = timestamp;
		}

		// renvoie des données reçues
		data_recu = UART5_ReadByte();
		if (data_recu != 0) {
			UART5_SendByte(data_recu);
		}
	}
	#endif

	#ifdef P2
	// Configuration des pins GPIO avec SPI5
	LCD_InitGPIO();
	GPIO_Config(GPIOF, 7, 2, 0, 3, 5); // SCLK
	GPIO_Config(GPIOF, 8, 2, 0, 3, 5); // MISO
	GPIO_Config(GPIOF, 9, 2, 0, 3, 5); // MOSI

	// Initialisation du module SPI
	SPI_Init(SPI5);
	SPI_Config(SPI5, 1, 16, 0, 0, 0, 0, 1, 0, 1);

	#endif

	#ifdef P3

	#endif
}

/*
 * Labo 2 :
#ifdef P1

	SysTick_Init(9000); // interruption a chaque 1ms
	GPIO_Config(GPIOC, 3, 3, 0, 0, 0); // Mode 3 pour analog
	GPIO_Config(GPIOG, 13, 1, 0, 0, 0); // LED

	ADC_Config(ADC1, 13);
	int conversion_count = 0;
	uint32_t sample = 0;
	uint64_t time = 0;
	int LED = 1;
	GPIO_writePIN(GPIOG, 13, LED);
	while (1){
		time = millis();
		if (time > conversion_count*100){ // 1 conversion a chaque 100ms
			conversion_count = conversion_count + 1;
			ADC_StartConvert(ADC1);
		}
		if(ADC_IsReady()){
			sample = ADC_GetSample(ADC1);
			LED = !LED;
			GPIO_writePIN(GPIOG, 13, LED);
			// Breakpoint ici pour avoir valeur sample
		}
	}
	#endif

	#ifdef P2   // pour bien dÃ©limiter la section du lab
	    // Initialisation du module PWM
	    PWM_Init();


	    // Cas 1 : Duty = 25 %, Freq = 100 Hz

//	    PWM_SetFrequency(100);
//	    PWM_SetDutyCycle(25);
	    // while(1);

	    // Cas 2 : Duty = 63 %, Freq = 400 Hz

//	    PWM_SetFrequency(400);
//	    PWM_SetDutyCycle(63);
	    // while(1);

	    // Cas 3 : Duty = 88 %, Freq = 1 kHz
	    PWM_SetFrequency(1000);
	    PWM_SetDutyCycle(88);

	#endif

	#ifdef P3
	ControleurLED_Init();

	    // Boucle principale :
	    //   - Si bouton pressé -> lire ADC -> appliquer intensité
	    //   - Si relacher -> éteindre LED
	    //   - Échantillonnage 10 Hz
	    while (1) {
	        uint8_t btn_state = GPIO_readPIN(GPIOA, 0);

	        if (btn_state) {
	            // bouton appuyé, lire ADC et appliquer intensité
	            ControleurLED_UpdateFromADCAndApply();
	        } else {
	            // bouton relaché, éteindre LED
	            ControleurLED_Off();
	        }

	        delai(100); // 100 ms pour freq de 10Hz
	    }
	 #endif
 */

