/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2025-09-29

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "GPIO.h"
#include "stm32f4xx.h"
#include <stdbool.h>
#include "adc.h"
#include "delai.h"
#include "pwm.h"
#include <stdio.h>

#define P1

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
//	#ifdef P1
//	GPIO_Config(GPIOC, 3, 3, 0, 0); // Mode 3 pour analog
//	ADC_Config(ADC1, 13);
//	SysTick_Init(9000); // interruption à chaque 1ms
//	uint32_t conversion_count = 0;
//	uint32_t sample = 0;
//	while (1){
//		if (millis() > conversion_count*100 ){ // 1 conversion a chaque 100ms
//			conversion_count++;
//			ADC_StartConvert(ADC1);
//		}
//		if(ADC_IsReady()){
//			sample = ADC_GetSample(ADC1);
//			// Breakpoint ici pour avoir valeur sample
//		}
//	}
//	#endif
//	{
	// #ifdef PARTIE_2_PWM   // pour bien délimiter la section du lab
	    // Initialisation du module PWM
	    PWM_Init();


	    // Cas 1 : Duty = 25 %, Freq = 100 Hz

//	     PWM_SetFrequency(100);
//	     PWM_SetDutyCycle(25);
	    // while(1);

	    // Cas 2 : Duty = 63 %, Freq = 400 Hz

//	     PWM_SetFrequency(400);
//	     PWM_SetDutyCycle(63);
	    // while(1);

	    // Cas 3 : Duty = 88 %, Freq = 1 kHz
	    PWM_SetFrequency(1000);
	    PWM_SetDutyCycle(88);

	    while (1) {
	    }
	// #endif

}
